#!/bin/bash
touch ../gpt2/$1.lock
source /home/teticio/virtualenvs/aventuras-con-textos-iyBfpclp/bin/activate
PYTHONIOENCODING=UTF-8 PYTORCH_TRANSFORMERS_CACHE=/var/www/html/deej-ai.online/.cache python3 ../GPT2.py "${@:2}"
rm ../gpt2/$1.lock
